# -*- coding: utf-8 -*-
"""data_shuffle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpX0PJPvvclk7sJbKKdurOL7hvfMZI7e
"""

# This code mainly divides the data into training data and test data

import random
import shutil
import os

data_path = './image_to_detect'
output_train = './data/train'
output_test = './data/test'
data1 = '/angles'
data2 = '/norm'
try:
    os.mkdir('./data')
    os.mkdir(output_train)
    os.mkdir(output_test)
    os.mkdir(output_train+data1)
    os.mkdir(output_train+data2)
    os.mkdir(output_test+data1)
    os.mkdir(output_test+data2)
except:
    print('dir already exists')
    pass
list = []
for i in os.listdir(data_path+data1):
    list.append(os.path.join(data_path,data1,i))
random.shuffle(list)
length = int(len(list)*0.7)
for ii in list[:length]:
    # print(ii)
    shutil.copy(data_path+ii,output_train+ii)
for ii in list[length:]:
    # print(ii)
    shutil.copy(data_path+ii,output_test+ii)

list = []
for j in os.listdir(data_path+data2):
    list.append(os.path.join(data_path,data2,j))
random.shuffle(list)
for ii in list[:length]:
    # print(ii)
    shutil.copy(data_path+ii,output_train+ii)
for ii in list[length:]:
    # print(ii)
    shutil.copy(data_path+ii,output_test+ii)
# print(list)